import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />  {/* Inclui o cabeçalho em todas as páginas */}
        <main className="container mx-auto p-4">
          {children} {/* Esta é a parte mais importante. É uma propriedade especial no React. O Next.js a utiliza como um placeholder onde o conteúdo da page.tsx ativa será renderizado.*/}
        </main>
      </body>
    </html>
  );
}