import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meu blog pessoal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${inter.className} bg-background text-foreground`}>
        <ThemeProvider>
          <Header /> {/* Inclui o cabeçalho em todas as páginas */}
          <main className="container mx-auto max-w-3xl p-4">
            {children}
            {/* Esta é a parte mais importante. É uma propriedade especial no React. O Next.js a utiliza como um placeholder onde o conteúdo da page.tsx ativa será renderizado. */}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
